### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by punkpeye** [iskakaushik/mcp-clickhouse#1]
I'm trying to start this server so I can mark the associated [listing](https://glama.ai/mcp/servers/9292900sx1) as tested.

### Current Behavior

This is my `Dockerfile`:

```Dockerfile
FROM python:3.13

RUN pip install uv

WORKDIR /app

RUN git clone https://github.com/iskakaushik/mcp-clickhouse .

WORKDIR /app/

RUN uv sync

CMD ["uv", "run", "mcp-clickhouse"]
```

When I run it, I get the following error:

```
error: Failed to spawn: `mcp-clickhouse`
  Caused by: No such file or directory (os error 2)

```

### Expected Behavior

The server should start correctly when using `uv run`.

### Suggested Improvement

Could you provide a complete example in the README showing how to start the server using uv run?

This would improve usability for developers and help automated systems like [Glama](https://glama.ai/mcp/servers) to test the server

**Comment by iskakaushik** [comment]
this should be fixed now, could you try rerunning?

**Comment by iskakaushik** [comment]
I added some automated tests as well.

**Comment by punkpeye** [comment]
Can confirm it is working. Thank you!
